name: smartmove
description: An app that keeps you going wherever you are.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_icons: ^1.0.0+1
  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.1
  firebase_core: ^0.4.2+1
  firebase_analytics: ^5.0.16
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.13.0+1
  firebase_database: ^3.0.7
  firebase_storage: ^3.1.5
  path: ^1.7.0
  google_sign_in: ^4.0.7
  provider: ^3.1.0+1
  intl: ^0.16.1
  intl_translation: ^0.17.10+1
  google_maps_flutter: ^1.0.2
  google_maps_webservice: ^0.0.18
  location: ^2.3.5
  geolocator: ^5.3.1
  flutter_polyline_points: ^0.2.4
  flutter_launcher_icons: ^0.8.0
  local_auth: ^0.6.3+2
  image_picker: ^0.6.0+17
  modal_progress_hud: ^0.1.3
  shared_preferences: ^0.5.5
  flutter_local_notifications: ^1.5.0+1
  connectivity: ^1.0.0
  share: ^0.6.5+4
  devicelocale: ^0.3.3
  dotted_border: ^1.0.7
  datetime_picker_formfield: ^1.0.0
  random_string: ^2.1.0
  bot_toast: ^2.2.1
  permission_handler: ^5.0.0
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  font_awesome_flutter: ^8.10.1
  styled_widget: ^0.2.2
  quick_actions: ^0.4.0+10
  flutter_markdown: ^0.5.1
  flutter_slidable: ^0.5.7
  flutter_statusbarcolor: ^0.2.3
  url_launcher: ^5.7.10
  introduction_screen: ^1.0.9
  photo_view: ^0.10.3
  add_2_calendar: ^1.4.0

flutter_icons:
  android: false
  ios: true
  image_path: "assets/IMG_0298.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/google-logo.png
    - images/giphy.gif
    - images/test.webp
    - assets/assetimages/ic_user_with_circle.png
    - assets/assetimages/buttons/ic_delete.png
    - assets/assetimages/buttons/ic_edit.png
    - assets/assetimages/buttons/ic_share.png
    - assets/bus_stops.json
    - assets/services.json
    - assets/mrt/mrt-dark.png
    - assets/mrt/mrt-light.png
    - assets/onboard/
    - lang/en.json
    - lang/zh.json
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
